// Generated by CoffeeScript 1.6.3
(function() {
  var Bug;

  Bug = (function() {
    function Bug(x, y) {
      this.x = x;
      this.y = y;
      this.plane = null;
      this.heading = 0;
    }

    Bug.prototype.move = function() {};

    Bug.prototype.getRefPoints = function() {
      var backAngle, leftAngle, points, rightAnge;
      points = [];
      points[points.length] = [this.x + 0.001 * Math.cos(this.degreesToRadians(this.heading)), this.y + 0.001 * Math.sin(this.degreesToRadians(this.heading))];
      rightAnge = this.degreesToRadians(this.heading - 90);
      points[points.length] = [this.x + 0.001 * Math.cos(rightAngle), this.y + 0.001 * Math.sin(rightAngle)];
      backAngle = this.heading + 180;
      points[points.length] = [this.x + 0.001 * Math.cos(backAngle), this.y + 0.001 * Math.sin(backAngle)];
      leftAngle = this.heading + 90;
      points[points.length] = [this.x + 0.001 * Math.cos(leftAngle), this.y + 0.01 * Math.sin(leftAngle)];
      return points;
    };

    Bug.prototype.putInPlane = function(plane) {
      return this.plane = plane;
    };

    Bug.prototype.degreesToRadians = function(degs) {
      return degs * (Math.pi / 180);
    };

    Bug.prototype.radiansToDegrees = function(rads) {
      return rads * (180 / Math.pi);
    };

    return Bug;

  })();

  this.Bug = Bug;

}).call(this);
