// Generated by CoffeeScript 1.6.3
(function() {
  var Bug;

  Bug = (function() {
    function Bug(x, y) {
      this.x = x;
      this.y = y;
      this.plane = null;
    }

    Bug.prototype.move = function() {};

    Bug.prototype.getRefPoints = function() {
      var backAngle, leftAngle, points, rightAngle;
      console.log("Bug heading: " + this.heading);
      points = [];
      points[points.length] = [this.x + 0.05 * Math.cos(this.degreesToRadians(this.heading)), this.y + 0.05 * Math.sin(this.degreesToRadians(this.heading))];
      rightAngle = this.degreesToRadians(this.heading - 90);
      points[points.length] = [this.x + 0.05 * Math.cos(this.rightAngle), this.y + 0.05 * Math.sin(this.rightAngle)];
      backAngle = this.degreesToRadians(this.heading + 180);
      points[points.length] = [this.x + 0.05 * Math.cos(backAngle), this.y + 0.05 * Math.sin(backAngle)];
      leftAngle = this.degreesToRadians(this.heading + 90);
      points[points.length] = [this.x + 0.05 * Math.cos(leftAngle), this.y + 0.05 * Math.sin(leftAngle)];
      return points;
    };

    Bug.prototype.putInPlane = function(plane) {
      return this.plane = plane;
    };

    Bug.prototype.degreesToRadians = function(degs) {
      return degs * (Math.PI / 180);
    };

    Bug.prototype.radiansToDegrees = function(rads) {
      return rads * (180 / Math.PI);
    };

    return Bug;

  })();

  this.Bug = Bug;

}).call(this);
