// Generated by CoffeeScript 1.6.3
(function() {
  var Bug1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Bug1 = (function(_super) {
    __extends(Bug1, _super);

    function Bug1(x, y, gx, gy) {
      this.x = x;
      this.y = y;
      this.gx = gx;
      this.gy = gy;
      Bug1.__super__.constructor.call(this, this.x, this.y);
      this.wallFollowing = false;
      this.firstLap = true;
      this.heading = 0;
      this.shortestPoint = [];
      this.encounteredObj = [];
    }

    Bug1.prototype.turnLeft = function() {
      return this.heading += 1;
    };

    Bug1.prototype.turnRight = function() {
      return this.heading -= 1;
    };

    Bug1.prototype.move = function() {
      if (!this.wallFollowing) {
        if (this.frontIsClear()) {
          this.orientTowardsGoal();
          this.x = this.x + 0.05 * Math.cos(this.degreesToRadians(this.heading));
          this.y = this.y + 0.05 * Math.sin(this.degreesToRadians(this.heading));
        } else {
          this.wallFollowing = true;
          if (this.rightIsClear()) {
            while (this.rightIsClear()) {
              this.turnRight();
            }
          } else if (!this.frontIsClear()) {
            while (!this.frontIsClear()) {
              this.turnLeft();
            }
          }
          this.x = this.x + 0.05 * Math.cos(this.degreesToRadians(this.heading));
          this.y = this.y + 0.05 * Math.sin(this.degreesToRadians(this.heading));
          this.shortestPoint = [this.x, this.y];
          this.encounteredObj = [this.x, this.y];
        }
      } else {
        if (this.rightIsClear()) {
          while (this.rightIsClear()) {
            this.turnRight();
          }
        } else if (!this.frontIsClear()) {
          while (!this.frontIsClear()) {
            this.turnLeft();
          }
        }
      }
      this.x = this.x + 0.05 * Math.cos(this.degreesToRadians(this.heading));
      this.y = this.y + 0.05 * Math.sin(this.degreesToRadians(this.heading));
      if (this.firstLap) {
        if (this.atPoint.apply(this, this.encounteredObj)) {
          this.firstLap = false;
        }
        if (this.dist(this.x, this.y, this.gx, this.gy) < this.dist(this.shortestPoint[0], this.shortestPoint[1], this.gx, this.gy)) {
          this.shortestPoint = [this.x, this.y];
        }
        if (this.atPoint(this.encounteredObj)) {
          return this.firstLap = false;
        }
      } else {
        if (this.atPoint.apply(this, this.shortestPoint)) {
          this.orientTowardsGoal();
          this.wallFollowing = false;
          this.firstLap = true;
          this.x = this.x + 0.05 * Math.cos(this.degreesToRadians(this.heading));
          return this.y = this.y + 0.05 * Math.sin(this.degreesToRadians(this.heading));
        }
      }
    };

    if (Bug1.plane !== null) {
      Bug1.plane.drawPoint(Bug1.x, Bug1.y);
    }

    Bug1.prototype.frontIsClear = function() {
      var refPoints, _ref;
      console.log("Bug1 heading: " + this.heading);
      refPoints = this.getRefPoints(this.heading);
      if (this.plane !== null) {
        return !(_ref = this.plane).checkCollision.apply(_ref, refPoints[0]);
      } else {
        return false;
      }
    };

    Bug1.prototype.rightIsClear = function() {
      var refPoints;
      refPoints = this.getRefPoints();
      if (this.plane !== null) {
        return !this.plane.checkCollision(refPoints[1]);
      } else {
        return false;
      }
    };

    Bug1.prototype.backIsClear = function() {
      var refPoints;
      refPoints = this.getRefPoints();
      if (this.plane !== null) {
        return !this.plane.checkCollision(refPoints[2]);
      } else {
        return false;
      }
    };

    Bug1.prototype.leftIsClear = function() {
      var refPoints;
      refPoints = this.getRefPoints();
      if (this.plane !== null) {
        return !this.plane.checkCollision(refPoints[3]);
      } else {
        return false;
      }
    };

    Bug1.prototype.orientTowardsGoal = function() {
      return this.heading = this.radiansToDegrees(Math.atan((this.gy - this.y) / (this.gx - this.x)));
    };

    Bug1.prototype.atPoint = function(px, py) {
      return this.dist(this.x, this.y, px, py) < 0.05;
    };

    Bug1.prototype.atGoal = function() {
      return this.atPoint(this.gx, this.gy);
    };

    Bug1.prototype.dist = function(x1, y1, x2, y2) {
      return Math.sqrt(Math.pow(x2 - x1, 2) + Math.pow(y2 - y1, 2));
    };

    Bug1.prototype.printPlane = function() {
      return console.log(this.plane);
    };

    return Bug1;

  })(Bug);

  this.Bug1 = Bug1;

}).call(this);
