// Generated by CoffeeScript 1.6.3
(function() {
  var Obstacle;

  Obstacle = (function() {
    function Obstacle(points, draw) {
      var g, i;
      this.points = points;
      this.draw = draw;
      this.poly = this.draw.polygon(this.points).fill('black').stroke({
        width: 1
      }).attr('id', "" + this.points[0][0] + " + " + this.points[0][1]);
      this.edges = [];
      i = 1;
      while (i < this.points.length) {
        g = new Line(this.points[i - 1][0], this.points[i - 1][1], this.points[i][0], this.points[i][1], this.draw);
        this.edges.push(g);
      }
      g = new Line(this.points[0][0], this.points[0][1], this.points[this.points.length - 1][0], this.points[this.points.length - 1][1], this.draw);
      this.edges.push(g);
      this.bb = document.getElementById(this.poly.attr('id')).getBBox();
    }

    Obstacle.prototype.intersectsPoint = function(x, y) {
      var i, l, p, pointsBeforePoint;
      pointsBeforePoint = [];
      if (!((this.bb.y < y && y < this.bb.y + this.bb.height))) {
        return false;
      }
      i = 0;
      l = new Line(0, y, this.draw.size()[0], y, this.draw, false);
      while (i < this.edges.length) {
        if (l.passesThroughLine(this.edges[i])) {
          p = l.intersection(this.edges[i]);
          if (p[0] <= x) {
            pointsBeforePoint.push(p);
          }
        }
        i++;
      }
      return !(pointsBeforePoint.length % 2);
    };

    return Obstacle;

  })();

  this.Obstacle = Obstacle;

}).call(this);
